FROM php:8.1-fpm-alpine

RUN apk add --no-cache \
    zlib-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql zip

# Install Bash
RUN apk add --no-cache bash

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
