version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #      - ./public:/var/www/proj
      - ../../:/app/:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    volumes:
      - ../../:/app
    depends_on:
      - db_local
    environment:
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=5
      - PHP_FPM_PM_START_SERVERS=2
      - PHP_FPM_PM_MIN_SPARE_SERVERS=1
      - PHP_FPM_PM_MAX_SPARE_SERVERS=3
    working_dir: /app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db_local
    environment:
      PMA_HOST: db_local
      PMA_PORT: 3306
    ports:
      - "8081:80"

  db_local:
    image: mariadb
    env_file: database.env
    volumes:
      - db_data:/var/lib/mysql
      - ./albion_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    restart: always

volumes:
  db_data: